apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: client
    name: client
spec:
  replicas: 1
  selector:
    matchLabels:                          
      app: client

 #-------------------------------> RollingUpdate definition
  strategy:
    type: RollingUpdate 
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 50%

#-------------------------------> Blueprint for Pod
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: crfitverse.azurecr.io/clientservice:$(Build.BuildId)
        ports:
        - containerPort: 80
        - name: health-port
          containerPort: 80
        resources:
          requests:
            cpu: "25m"
            memory: "32Mi"
          limits:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 88
      targetPort: 80

